### ISSUE TITLE
Case study 3 - exercise 18

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management#10]
# Module: case study 3
#### Step: 10

Description of issue
•	Please see here also the picture ref. exercise 18, part create a new purchase order – step 10: “Confirm” is greyed out.
unsure how to proceed

**Comment by hakimmartin** [comment]
Unable to reproduce. I have completed all lab steps and the confirm button is not greyed out. Attaching image @chaast 
![image](https://user-images.githubusercontent.com/71838770/135311721-825c000d-37d6-4264-bede-b2fca255ce74.png)
