### ISSUE TITLE
Case Study 5 - various issues in both exercises (3 in total) 

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management#35]
# Case Study: 5
#### Step: 01
Description of the issue:  there is no order 004262 -- please update the instruction to pick order 004137.

# Case Study: 5
#### Step: 04 
Description of the issue: there is no apples group - hence unable to proceed -- please update the instruction to clarify which item group to pick in the wizard

# Case Study: 5
#### Step: 04 
Description of the issue: there is no 60 intercompany planning group - hence unable to proceed --please update the instruction to clarify which planning to pick.

**Comment by chaast** [comment]
could I please have someone look into this for me? I am about to deliver this course again next week...

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review has solved the issue for Case Study 5, Exercise 1, Step 1 with pull request #58.

MOC Labs Review has solved the issue for Case Study 5, Exercise 2, Step 4 with pull request #59, #61, #62.

MOC Labs Review confirms the issue for Case Study 5, Exercise 2, Step 4: Run an intercompany master plan.

**Comment by chaast** [comment]
thank you for looking into this for me and thank you for the pull requests

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! Module 6 / Case study 5 / Exercise1 Step 1 and Module 6 / Case study 5 / Exercise 2 Step 4. We are reviewing this and will provide an update once a resolution is in place.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.
