### ISSUE TITLE
Link to HTML view

### ISSUE THREAD

**Issue by 365freelancer** [MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management#4]
Hi,
Where do I find the HTML pages for this lab?
Br
Johnny Raadshøj

**Comment by Tarekeldin** [comment]
Hi,
here is the page where you will see all the lab exercises https://github.com/MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management/tree/master/Instructions/Labs
please let me know if you have more questions 

Yours,
T

**Comment by 365freelancer** [comment]
Hi T,
The link you provided is to the list of md files and not the HTML view.
Take a look at for example https://microsoftlearning.github.io/MB-200-Dynamics365CustomerEngagementCore-/
Please advise

**Comment by Tarekeldin** [comment]
Hello,
The HTML page is here: https://microsoftlearning.github.io/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management/
 please check and let me know if you have any question.

sincerely,
T
