### ISSUE TITLE
Case Study 4 -- Exercise 2 -- step 11

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management#48]
I previously had an issue ref. Case Study 4 -  exercise 2  -- the issue is still there... 

Previously the answer was that the Results button is next to the Add and Remove buttons, which indeed i can see... but what i cannot see is the instruction in Step 11 of this exercise "in the bottom pane, select the line where sequence is 10 (length)....

Results button is right next to the Add and Remove buttons. Attaching a screenshot for reference, this will show open another window. @chaast 
![image](https://user-images.githubusercontent.com/71838770/135312884-3a6136df-0da8-49b7-8087-ded25a2aca7b.png)

_Originally posted by @hakimmartin in https://github.com/MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management/issues/11#issuecomment-930349712_

so...
* i can only see a line on the Test group that i have just created where the sequence number is 1 - do i proceed with that? if so, i cannot carry out step 13 - i cannot enter the value of 100 in the result field...
* Step 15 is also unable to be carried out, because i do not have a line where sequence is 20
![image](https://user-images.githubusercontent.com/89986870/184015866-b5cb18ed-8710-4081-87bf-8a72d5fafc69.png)

![image](https://user-images.githubusercontent.com/89986870/184015934-d10f1e01-a675-4d80-ad1c-a19245564c0b.png)

* i then tried to addd "Test enclosure measure (sequence number 10) to the grid -- but upon clicking result I cannot proceed due to the message on screen "the outcome must be associated with the test variable" - how do i proceed with this?

![image](https://user-images.githubusercontent.com/89986870/184016994-86408e1e-046a-4c53-9c68-97f9e2873d24.png)

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by chaast** [comment]
thank you. Has a pull request been initiated?

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! Module 5 / Case study 4 / Exercise 2 Step 11. We are reviewing this and will provide an update once a resolution is in place.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by mstall1ngs** [comment]
In this exercise, you will select the quality order line for item number M0061. This will update the bottom grid to the test and display Sequence number 10 Test Concentration. Note: when viewing item number M0061, notice that the Add and Remove buttons are greyed out. 

![image](https://user-images.githubusercontent.com/104943975/221390555-abfb8025-a798-4c71-9cc4-775460dcbb58.png)

**Comment by mstall1ngs** [comment]
> thank you. Has a pull request been initiated?

There are no issues direct of the system. Pull request not initiated nor required.
