### ISSUE TITLE
Case study 2a - exercise 1

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management#6]
# Module: Case study 2A
#### Step: step 7 click refresh a few times and wait until the work items shows records

Description of issue
waited over 10 minutes, nothing shows in work items so cannot proceed.

**Comment by hakimmartin** [comment]
Could not repro. The results showed up a few seconds after hitting workflow history. Attaching image @chaast 
![image](https://user-images.githubusercontent.com/71838770/135298681-7d380bc3-2fed-47dc-bfad-8d43b2910cbb.png)
