### ISSUE TITLE
Case study 2a - exercise 2

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management#7]
# Module: Case study 2A
#### Step: 6/7/8 (after I opened the RFQ for US-111 I cannot edit quantity, unit or unit price.

Description of issue
I have tried to click “manage reply” as well as the direct instruction to click on the rfq number) there appears to be a disconnect from the previous step - unsure how to proceed

**Comment by hakimmartin** [comment]
You have to click edit RFQ in order to edit the quantity, unit, and price. Attaching the screenshot 
![image](https://user-images.githubusercontent.com/71838770/135305659-86ffe561-6b6d-4e09-b1a0-f9aa72a67766.png)
