### ISSUE TITLE
NEED TO RE-OPEN PREVIOUS ISSUE -- PROBLEM WAS NOT FIXED: Case Study 4 - Exercise 2 -- step 11 & step 15

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management#76]
(https://github.com/MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management/issues/48#issue-1335175626)

The issue persists!

the response from @mstall1ngs  --- is not fixing the issue.. you cannot change the test result field value field to 100 on the item M0061. Nor does this item give a line with sequence of 20. 
The other line items on the page do not have these options either.

![image](https://github.com/MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management/assets/89986870/bfabdefb-558c-4c95-afe8-424e6b493d40)

Can someone please have a look and issue the pull request or update the step instructions -- which is what I requested last year, in August 2022 as well.

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! Module 5 / Case study 4 / Exercise 2 Step 11 and Step 15. We are reviewing this and will provide an update once a resolution is in place.

**Comment by chaast** [comment]
Hi Michelle, thank you for your message. I am grateful for your help.

**Comment by mstall1ngs** [comment]
@chaast, there have been some recent updates and this is currently being tested. Per the resolution, the steps will be updated accordingly. Thanks for your patience!

**Comment by mstall1ngs** [comment]
Thanks again for providing insight on this. The lab instructions have been updated accordingly.
