### ISSUE TITLE
Case Study 5 - Exercise 2 - Run an intercompany master plan - step 11 error

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management#77]
# Case Study: 05
#### Step: 11

Description of issue: mutliple errors as per screenshot - not sure if this is expected behaviour due to practise environment setup...

![image](https://github.com/MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management/assets/89986870/4d6e4c85-dc73-4ed2-af6a-ba7dfe5b25c1)

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! Module 6 / Case study 5 / Exercise 2. We are reviewing this and will provide an update once a resolution is in place. It would be helpful if we had additional clarification regarding this issue that you are experiencing.
 
Please elaborate more on this request. 
****ALH Hoster:** 
**Lab environment version:** 
**Module/Case Study, Exercise and Steps: **Module 6 / Case study 5 / Exercise 2****
**Which section of this exercise did you experience the issue?** This exercise currently has 3 sections that contain step 11.
**Repro Steps:****

**Comment by chaast** [comment]
Hi Michelle, thank you for coming back to me. The issue occurred right at the very end. The very last exercise, the very last couple of steps.

Lab Hoster: Skillable
ID | 31021003
Host | EU-HV16
Datacenter | East US

Dynamics product version as per image below:
![image](https://github.com/MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management/assets/89986870/8f228f84-80bb-4e27-a818-eeab0e7d21ad)

**Comment by mstall1ngs** [comment]
In the exercise, I was unable to replicate and may have been resolved with the latest release. 

![image](https://github.com/MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management/assets/104943975/cb919991-4baa-4fdc-b984-1d20e1110e94)


After running the intercompany master plan, the job was added for batch processing
![image](https://github.com/MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management/assets/104943975/6dca8665-164b-4935-a412-f944aa0bfb88)
