### ISSUE TITLE
NEED TO RE-OPEN PREVIOUS ISSUE -- PROBLEM WAS NOT FIXED : Case Study 3 - exercise 19 -- sales order not sent to credit management, unable to proceed with remainder of lab

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management#78]
ISSUE NEEDS TO RE-OPENED.. previously reported... but sadly the instructions in the labs were not updated, although this was previously requested as well!!

It is not good enough to just report the workaround on github - for learners, the instructions need to be clear in the lab! to have labs that have "errors" / "incomplete instructions" results in a negative learning experience for course delegates!

https://github.com/MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management/issues/47#issue-1333751048

![image](https://github.com/MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management/assets/89986870/028131db-3357-4479-8eb8-9dcf08096977)

**Comment by mstall1ngs** [comment]
Hi @chaast, 
Thanks for reporting this on GitHub! Module 4 / Case study 3 / Exercise 19 Step 11. We are reviewing this and will provide an update once a resolution is in place. The provided fix in #47 was not a workaround. It would be helpful if we had additional clarification regarding this issue that you are experiencing as it was previously resolved in #47. In the previously reported issue, you were unable to add values in the reservation field on the Reservation form in reference to the Sales order. Per my comments on #47, in the screenshot that you provided, I did not see the order line. The order line would need to be checked in the Sales order lines FastTab to view it in the Reservation form. The instructions were not updated as this is signified and indicated in step 1 of Reserve stock for the order section of Exercise #19.
![image](https://github.com/MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management/assets/104943975/b8aab42f-bcd0-4321-8fa8-78f762440309)

**Comment by chaast** [comment]
Hi Michelle, thank you for coming back to me. 
Lab Hoster: Skillable
ID | 31021003
Host | EU-HV16
Datacenter | East US

Dynamics version as per below image. I will take screenshots of each preceeding step as I go along so you can see what is happening...

![image](https://github.com/MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management/assets/89986870/bae51867-0aa9-48e1-a660-9205edae575a)

**Comment by chaast** [comment]
Please find herewith a detailed description of where the issue arises. 
I will try explain as best as I can from the beginning of **exercise 19 - Process outbound shipments.**

*** Initiating an Outbound shipment**
   - Receive and confirm sales order for A0001 = all ok
   - Receive stock for the order = all ok as per image below.
  
![image](https://github.com/MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management/assets/89986870/422502c0-10f9-4327-bd47-d5215ddcb851)

  - Create an outbound transportation load = all ok as per image below
  
![image](https://github.com/MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management/assets/89986870/09f4413e-846c-4a08-9dac-8faaf744d773)

*** Creating a Consolidated Shipment**
   - set up parameters for consolidated shipments = all ok
   - add a new line to a sales order - entering A0002 - causes the notification of the fact that the order was not sent to credit management on completing step 10. As per image below... this is where things start to look wrong....

![image](https://github.com/MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management/assets/89986870/097b6a2e-3a92-4fae-908d-8215322168c9)

If I ignore this warning and try to proceed to
   - Reserve stock for the order, steps 1-5 do not give me the option to add 5 in the reservation field for the line A0002... Hence i am unable to proceed with the exercise.... Images below....
  
Step 1 - In the sales order details form, select one of the order lines in the sales order lines fastTab - as per below:
![image](https://github.com/MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management/assets/89986870/d57fdf25-27b7-4a54-a63c-5d74a42cd144)

Step 2: click the inventory drop-down arrow and select reservation - this time the form looks different from the first time doing this when I had only A0001 on the sales order.
Step 3: in the reservation form, in the reservation field, enter 5 - but i can't -- the form is empty of sales lines and thus there is no option to update the reservation field. Image below.

![image](https://github.com/MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management/assets/89986870/ba49681d-f9fd-4d6d-91f4-bb6203b87fe4)

**Comment by mstall1ngs** [comment]
Thanks @chaast for providing the elaborate details and for bringing this to my attention. I did not run into any issues during replication with errors on the sales order pertaining to credit management nor issues with reservations, but to minimize the confusion, I've update the lab instructions to reflect the details on the exclusion and where to navigate to update the blocking rules for credit management. 

Sales order 000835

![image](https://github.com/MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management/assets/104943975/f9cdaaa2-a3a5-4410-b8d7-40410608b904)

Reservation lot
![image](https://github.com/MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management/assets/104943975/dd421724-e0d8-41d6-8fd9-54bbc520113b)

**Comment by mstall1ngs** [comment]
Please view the above resolution.
