### ISSUE TITLE
Case study 4 - Ex 2 create manual quality order - unable to proceed after step 14

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management#79]
# Case Study 4
### Step: 14

Description of issue
* there is no line where the sequence is 20 on any of the quality orders in the list... 
* unable to complete steps 14-16 of this exercise.

Image of repro steps
![image](https://github.com/MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management/assets/89986870/140b35c5-0bf9-4462-90c3-7d0460a98273)

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! Module 5 / Case study 4 / Exercise 2 Step 14. This has been updated accordingly.
