### ISSUE TITLE
case study 2a - exercise 4

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management#8]
Exercise 4
Part: create a purchase order
Step 10  Generate > Product receipt is greyed out and not an option after order is created (even though delivery is set to today)… waited over 10 minutes, nothing shows.

**Comment by hakimmartin** [comment]
This exercise was re-tested and we were able to generate the product receipt.
