### ISSUE TITLE
Case Study 3 - SRHQ - Seahorse Retailers legal entity does not exist in lab environment

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management#80]
# Case Study 3
#### Step: 01

Description of issue
* In the introduction is sets the scene for SRHQ - however, this is not available from the legal entity selection list in the blue ribbon
Which legal entity should i pick instead?

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! Module 4/ Case study 3/ Exercise 1. We are reviewing this and will provide an update once a resolution is in place.

**Comment by mstall1ngs** [comment]
The descriptive in the scenario is that "you are asked to assist the warehouse manager for SRHQ Seahorse Retailers". You would use USMF for this practice.
