### ISSUE TITLE
Case Study 5 - Ex 2, last task - run an intercompany masterplan error message

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management#81]
# Case Study 5
##Exercise 2
#### Step: 12

Description of issue
* system pops up with an error
"the menu item with name intercompanyreqcalschedule could not be opened"

therefore unable to see the run of the plan.

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! Module 6 / Case study 5 / Exercise 2. We are reviewing this and will provide an update once a resolution is in place.

**Comment by JorritMertens** [comment]
This error is still not resolved in the lab please update the version. And working times in the calenders because the current instructions are not working for the students
