### ISSUE TITLE
Case Study 2B, Ex 2: No commission transactions displayed

### ISSUE THREAD

**Issue by SkillableMG** [MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management#83]
- Case study 2B Sales and marketing
- Exercise <span>#</span>2 Create and review a sales order for commission
- Review the registered sales commissions
- step 5

At the above-referenced step, no commission transactions are visible in our testing.

Increasing the "To" date to end of 2024 at the previous task "Invoice a sales order that qualifies a salesperson for a commission" step 3 was tested as a potential workaround, but this was not successful.

![image](https://github.com/MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management/assets/134323425/696690ba-4108-466b-a17f-335dcc74dcd1)

**Comment by mstall1ngs** [comment]
Hi @SkillableBB,

Thanks for reporting this on GitHub! Module 3 / Case study 2B / Exercise 2. We are reviewing this and will provide an update once a resolution is in place, but it would be helpful if we had additional clarification regarding this issue that you are experiencing. Any additional details that you are able to provide is greatly appreciated!

**Comment by mstall1ngs** [comment]
Hello, 

I was able to replicate the issue. Below are the following repo steps:

1. Set up customer groups for commission, commission item groups, commission sales groups and commission rates by navigating to **Sales and marketing** > **Commissions** > **Customer groups for commission**
2. Create a **New** Commision calculation 
![image](https://github.com/MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management/assets/104943975/b4ed513d-32eb-4534-ab03-bafcbce26846)
3. Navigate to **Sales and marketing** > **Commissions** > **Item groups**
4. Create a **New** Item group
![image](https://github.com/MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management/assets/104943975/161872de-97f7-4698-9b9d-ab83aa5c24e9)
5.  Navigate to **Sales and marketing** > **Commissions** > **Sales groups**
4. Create a **New** Sales group to represent Sales reps US
![image](https://github.com/MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management/assets/104943975/2a0a8383-2c89-44a6-8ddf-0f33f1231870)


Here's relevant content: Set up of sales commission rules for commission groups and commission rates](https://learn.microsoft.com/en-us/dynamics365/supply-chain/sales-marketing/tasks/set-up-sales-commission-rules#set-up-commission-groups-and-commission-rates) and [Assign a commission group to a customer and a product](https://learn.microsoft.com/en-us/dynamics365/supply-chain/sales-marketing/tasks/set-up-sales-commission-rules#assign-a-commission-group-to-a-customer-and-a-product) would need to be configured.

To minimize the confusion, I've updated the lab instructions to reflect the details on the setting up sales commission rules and assigning a commission group to a customer. 

Results for commission transactions
![image](https://github.com/MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management/assets/104943975/cbbc8ddd-d1a5-4c3b-892b-6cba679ecabe)
