### ISSUE TITLE
Exercise #4 Create a purchase order for delivery to multiple sites

### ISSUE THREAD

**Issue by 365freelancer** [MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management#85]
# Module: 00
#### Step: 13

Description of issue
Select "Registered quantity" in the Quantity field - not possible - must be "ordered quantity"

Repro steps:

1.
1.
1.

**Comment by 365freelancer** [comment]
Try to do the exercise and you will understand what I report.

//Johnny

________________________________

**Comment by mstall1ngs** [comment]
Thanks Johnny for responding. The issue that you created has no detailed description of the issue nor repro steps that you took to get an error. Repro steps help us to break/fix the issue, as we would know exactly what to look for, and provide a more faster resolution. Please elaborate on this request. Are you able to provide details on the lab hoster and version that you are using? Any additional details that you are able to provide is greatly appreciated!
