### ISSUE TITLE
Trainer prep guide - Case study 6 is missing

### ISSUE THREAD

**Issue by 365freelancer** [MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management#86]
# Module: 00
#### Step: 00

Description of issue
Case study 6 is listed on page 11 in the Trainer prep guide but not included 

Repro steps:

1.
1.
1.

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! We are reviewing this and will provide an update once a resolution is in place, but it would be helpful if we had additional clarification regarding this issue that you are experiencing. Any additional details that you are able to provide is greatly appreciated!

Please elaborate more on this request.
ALH Hoster:
Lab environment version:
Is this your first encounter with this error?
Which section of this exercise did you experience the issue? 
Repro Steps:

**Comment by 365freelancer** [comment]
Try to do the exercise and you will understand what I report.

//Johnny

________________________________

**Comment by mstall1ngs** [comment]
Thanks, Johnny for responding. There are no associated labs with this as this is a trainer prep guide. We are reviewing this and will provide an update once a resolution is in place.
