### ISSUE TITLE
Case study 3A Warehouse management - SRHQ company does exist

### ISSUE THREAD

**Issue by 365freelancer** [MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management#87]
# Module: MB-330
#### Step: 0

Description of issue
"You were asked to help the warehouse manager for SRHQ Seahorse Retailers. He is responsible for building and designing the structure for the warehouse management system."

I see that the product P9500 mentioned later is released to USP2, so I guess the company should be USP2 and not SRHQ

Repro steps:

1.
1.
1.

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! We are reviewing this and will provide an update once a resolution is in place, but it would be helpful if we had additional clarification regarding this issue that you are experiencing. Any additional details that you are able to provide is greatly appreciated!

Please elaborate more on this request.
ALH Hoster:
Lab environment version:
Is this your first encounter with this error?
Which section of this exercise did you experience the issue? 
Repro Steps:

**Comment by 365freelancer** [comment]
Try to do the exercise and you will understand what I report.

//Johnny

________________________________

**Comment by mstall1ngs** [comment]
Thanks, Johnny, for responding. Item 9500 is in Ex 5 for PO creation, however, in Ex 4, you are setting up mobile device configurations in both legal entities. 

The descriptive in the scenario is that "you are asked to assist the warehouse manager for SRHQ Seahorse Retailers". You would use USMF for this practice.
