### ISSUE TITLE
Set warehouse selection to "Warehouse"

### ISSUE THREAD

**Issue by 365freelancer** [MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management#88]
# Module: MB-330
#### Step: 3

Description of issue
To be able to set the site "3" the user must change the "Warehouse selection" to "Warehouse"
Repro steps:

1.
1.
1.

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! We are reviewing this and will provide an update once a resolution is in place, but it would be helpful if we had additional clarification regarding this issue that you are experiencing. Any additional details that you are able to provide is greatly appreciated!

Please elaborate more on this request.
ALH Hoster:
Lab environment version:
Is this your first encounter with this error?
Which section of this exercise did you experience the issue? 
Repro Steps:

**Comment by 365freelancer** [comment]
Try to do the exercise and you will understand what I report.

//Johnny

________________________________
