### ISSUE TITLE
MB-330 Sales commission can't be calculated

### ISSUE THREAD

**Issue by 365freelancer** [MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management#89]
# Module: MB-330
#### Step: Select Details > Commission transactions.

Description of issue
"Assign a commission group to a customer and a product" must happen before "Invoice a sales order that qualifies a salesperson for a commission" otherwise "Review the registered sales commissions" will fail.

Repro steps:

1.
1.
1.

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! We are reviewing this and will provide an update once a resolution is in place, but it would be helpful if we had additional clarification regarding this issue that you are experiencing. Any additional details that you are able to provide is greatly appreciated!

Please elaborate more on this request.
ALH Hoster:
Lab environment version:
Is this your first encounter with this error?
Which section of this exercise did you experience the issue? 
Repro Steps:

**Comment by 365freelancer** [comment]
Try to do the exercise and you will understand what I report.

//Johnny

________________________________

**Comment by mstall1ngs** [comment]
Thanks Johnny for responding. The issue that you created has no detailed description of the issue nor repro steps that you took to get an error. Repro steps help us to break/fix the issue, as we would know exactly what to look for, and provide a more faster resolution. Please elaborate on this request. Are you able to provide details on the lab hoster and version that you are using? Any additional details that you are able to provide is greatly appreciated!
