### ISSUE TITLE
No stock of A0002 on site 5

### ISSUE THREAD

**Issue by 365freelancer** [MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management#90]
# Module: MB-330-Microsoft-Dynamics-365-Supply-Chain-Management
#### Step: 6

Description of issue
Please use site 2 or 4 with 10 pcs on stock, and not site 5
Repro steps:

1.
1.
1.

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! We are reviewing this and will provide an update once a resolution is in place, but it would be helpful if we had additional clarification regarding this issue that you are experiencing. Any additional details that you are able to provide is greatly appreciated!

Please elaborate more on this request.
ALH Hoster:
Lab environment version:
Is this your first encounter with this error?
Which section of this exercise did you experience the issue? 
Repro Steps:

**Comment by 365freelancer** [comment]
Try to do the exercise and you will understand what I report.

//Johnny

________________________________
