### ISSUE TITLE
Slide Deck permissions

### ISSUE THREAD

**Issue by LaurieHeer** [MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management#92]
The training slides have some permissions issues on Deck 1 and Deck 5. Looks like they might be locked for non-Microsoft employees.

**Comment by mstall1ngs** [comment]
@LaurieHeer The security measures on the decks were updated ensure compliance. The sensitivity was updated over 2 hours ago and posted to the LDC. When was the last time that you pulled the ppts?

**Comment by LaurieHeer** [comment]
About 5 hours ago. Pulling them again to see if I can open.

**Comment by mstall1ngs** [comment]
@LaurieHeer Great! Please keep me posted! If they need more info on how to access you can point them here:
[Current Courseware Downloading Process - Microsoft Community Hub](https://techcommunity.microsoft.com/t5/mct-program-announcements/current-courseware-downloading-process/ba-p/4196123)

**Comment by LaurieHeer** [comment]
I pulled a fresh copy from the LDC and they all open now. Thanks for including the link to the new process - that's very helpful! Have a great day and thanks for the lighting speed response!

**Comment by mstall1ngs** [comment]
We value our MCT community. Thanks for being on the train that helps us to empower every person and every organization to achieve more! Have an awesome day, @LaurieHeer
